export const services = [
  {
    id: "cybersecurity",
    title: "Cybersecurity",
    description: "Comprehensive security solutions to protect your digital assets and infrastructure.",
    features: [
      "Security posture assessment & gap analysis",
      "SOC setup and threat monitoring (SIEM, SOAR, 24/7 alerting)",
      "Incident response & digital forensics",
      "Cloud security hardening (AWS, Azure, GCP)",
      "Penetration testing & vulnerability management",
      "Compliance readiness (ISO 27001, SOC 2, GDPR, HIPAA, PCI DSS)",
      "Security awareness training & policy development",
    ],
    icon: "shield",
  },
  {
    id: "devsecops",
    title: "DevSecOps",
    description: "Integrate security into your development lifecycle for faster, safer deployments.",
    features: [
      "DevSecOps framework implementation (DevSecOps, DevOps, SecOps)",
      "Security automation & orchestration (CI/CD pipeline security, GitOps)",
      "Cloud native security (Container security, Kubernetes security)",
      "API security & authentication (OAuth, JWT, API key management)",
      "Microservices security & monitoring",
      "DevSecOps toolchain integration (SonarQube, Checkmarx, Veracode)",
    ],
    icon: "code",
  },
  {
    id: "ai",
    title: "AI & Machine Learning",
    description: "Leverage AI and ML to drive innovation and automate complex processes.",
    features: [
      "AI strategy & roadmap development",
      "Machine learning model development & deployment",
      "MLOps pipeline setup & automation",
      "Natural language processing (NLP) solutions",
      "Computer vision & image recognition",
      "AI-powered automation & chatbots",
      "Model monitoring & performance optimization",
    ],
    icon: "brain",
  },
  {
    id: "data",
    title: "Data Analytics",
    description: "Transform your data into actionable insights with advanced analytics solutions.",
    features: [
      "Data strategy & architecture design",
      "Data pipeline development (ETL/ELT)",
      "Business intelligence & reporting dashboards",
      "Data warehousing & data lakes",
      "Real-time analytics & streaming",
      "Predictive analytics & forecasting",
      "Data governance & quality management",
    ],
    icon: "database",
  },
  {
    id: "Cloud Engineering Services",
    title: "Cloud Engineering",
    description: "Transform your data into actionable insights with advanced analytics solutions.",
    features: [
      "Cloud Architecture & Migration",
      "Cloud Infrastructure Build & Automation",
      "Cloud Security Engineering",
      "Serverless & Modern Application Development",
      "Cost Management & Operational Optimisation",
      "Multi-Cloud & Hybrid Cloud Integration",
      "Disaster Recovery & Business Continuity Engineering",
    ],
    icon: "database",
  },
  {
    id: "Cloud Security Services",
    title: "Cloud Security",
    description: "Transform your data into actionable insights with advanced analytics solutions.",
    features: [
      "Cloud Security Posture Management (CSPM)",
      "IAM Zero Trust Architecture",
      "Cloud Compliance & Governance (ISO 27001, GDPR)",
      "Threat Detection & SIEM Integration",
      "Secure Cloud Architecture (Network, VPC, Firewalls)",
      "Disaster Recovery (DR) & Resilience Engineering",
      "Data Protection, Encryption & Key Management (KMS/HSM)",
    ],
    icon: "database",
  },
  {
    id: "devOps",
    title: "DevOps",
    description: "Integrate security into your development lifecycle for faster, safer deployments.",
    features: [
      "CI/CD Pipeline Setup & Automation)",
      "Infrastructure as Code (Terraform)",
      "Kubernetes Deployment & Management",
      "Cloud Infrastructure Setup & Optimization",
      "DevSecOps Pipeline Security",
      "Monitoring & Observability Setup",
      "Dockerization & Containerization",
    ],
    icon: "code",
  },
  {
    id: "Project Management & Agile Delivery",
    title: "Project Management & Agile Delivery",
    description: "Transform your data into actionable insights with advanced analytics solutions.",
    features: [
      "Agile transformation & coaching; Shifting teams from waterfall to agile frameworks.",
      "PMO setup & governance; Establishing processes, templates, and reporting for project offices.",
      "Program/portfolio management; Coordinating multiple related projects for large initiatives.",
      "Scrum & sprint delivery management; End-to-end delivery of software or transformation programs.",
      "Stakeholder communication & risk tracking; Managing expectations and dependencies effectively.",
      "Resource and timeline optimization; Ensuring cost-effective and on-time delivery.",
      "Change management & adoption strategy; Ensuring business users embrace new systems or processes.",
    ],
    icon: "database",
  },
  {
    id: "Technology Strategy Consulting",
    title: "Technology Strategy Consulting",
    description: "Transform your data into actionable insights with advanced analytics solutions.",
    features: [
      "Digital transformation roadmaps; Aligning IT investments with business strategy.",
      "IT modernization planning; Upgrading legacy systems to cloud-native, API-driven architecture.",
      "Cloud migration strategy; Planning phased migration with cost and security controls.",
      "Vendor/tool selection & technology stack advisory; Helping choose the right technologies for scale.",
      "IT risk and cost optimization; Reducing spend and improving performance across IT assets.",
      "Enterprise architecture design; Building future-ready, modular IT systems.",
      "Innovation enablement; Identifying emerging tech (AI, blockchain, IoT) opportunities.",
    ],
    icon: "database",
  },
  {
    id: "Digital Infrastructure Strengthening",
    title: "Digital Infrastructure Strengthening",
    description: "Transform your data into actionable insights with advanced analytics solutions.",
    features: [
      "Cloud infrastructure setup & optimization; multicloud & hybrid environments for performance and resilience.",
      "Network architecture review & redesign; Improving connectivity, redundancy, and speed.",
      "Infrastructure as Code (IaC) automation; Terraform, Ansible, or CloudFormation deployments.",
      "Disaster recovery & backup planning; Ensuring business continuity.",
      "Scalability & performance tuning; Reducing downtime and latency for critical systems.",
      "Monitoring & observability setup; Implementing tools like Prometheus, Grafana, or Datadog.",
      "	DevOps enablement; CI/CD pipelines, containerization, and automation integration.",
    ],
    icon: "database",
  },
  {
    id: "Operational Streamlining and Risk Reduction",
    title: "Operational Streamlining and Risk Reduction",
    description: "Transform your data into actionable insights with advanced analytics solutions.",
    features: [
      "CProcess mapping & bottleneck identification; Finding inefficiencies in existing workflows.",
      "Automation of manual processes; RPA, workflow orchestration, and low-code solutions.",
      "Operational risk assessment & mitigation; Identifying and controlling business-critical risks",
      "Cost reduction through optimization; Streamlining vendors, licenses, and redundant systems",
      "Compliance & audit process automation; Making governance faster and error-free.",
      "Service performance measurement (SLAs & KPIs); Building transparency in operations",
      "Continuous improvement frameworks (Lean, Six Sigma); Driving measurable efficiency gains.",
    ],
    icon: "wheel",
  },
] as const;

export const interestOptions = [
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "devsecops", label: "DevSecOps" },
  { value: "ai", label: "AI & Machine Learning" },
  { value: "data", label: "Data Analytics" },
] as const;

export const brandColors = {
  primary: "#0a0f28",
  secondary: "#1abc9c",
  neutral: "#bdc3c7",
} as const;
